# Generated by Django 5.2.4 on 2025-08-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_comment_update_at_remove_post_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='past',
            new_name='post',
        ),
    ]
